[package]
name = "gbx"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
description = "A (incomplete) GameBox (.Gbx) file reader and writer for Trackmania (2020)"
repository = "https://github.com/jussyDr/gbx"
license = "GPL-2.0"
categories = ["encoding", "parser-implementations"]

[[bench]]
name = "bench"
harness = false

[profile.bench]
debug = true

[dependencies]
lzo1x = { path = "../lzo1x" }
num_enum = "0.5.7"
serde = { version = "1.0.152", features = ["derive"], optional = true }

[dev-dependencies]
anyhow = "1.0.68"
base64 = "0.21.0"
criterion = "0.4.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
sha2 = "0.10.6"

[package.metadata.docs.rs]
features = ["serde"]
