name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toolchain: 1.62.0
            features: 
          - toolchain: stable 
            features:
          - toolchain: stable 
            features: serde
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose --features "${{ matrix.features }}"
    - name: Run tests
      run: cargo test --verbose --features "${{ matrix.features }}"
